### ISSUE TITLE
System.ArgumentOutOfRangeException: 'minValue' cannot be greater than maxValue.

### ISSUE THREAD

**Issue by juanonsoftware** [alexcpendleton/NLipsum#2]
Hello,

Sometime I got this problem, do you think it comes from the library?

![image](https://cloud.githubusercontent.com/assets/742950/11992518/9e978e78-aa59-11e5-9c92-9c38e61e52c1.png)

Thanks for useful package

**Comment by juanonsoftware** [comment]
This is how I call Nlipsum's method

            var paragraph = new Paragraph(1, 10);
            var generator = new LipsumGenerator();
            var content = string.Join(Environment.NewLine, generator.GenerateParagraphs(2, paragraph));

**Comment by nvivo** [comment]
Having the same problem. Looks like the LipsumGenerator has no words internally to choose from.

**Comment by alexcpendleton** [comment]
A LipsumGenerator needs to have its source text injected. Could you try using the constructor that takes a string and a boolean?

```LipsumGenerator lipsum = new LipsumGenerator(Lipsums.LoremIpsum, false);```

I realize this is not ideal and would've done it differently had I written it today. I originally wrote this for myself making use mostly of the static methods.

**Comment by juanonsoftware** [comment]
Yes, I have used the second constructor also and it works fine. Thanks for your great work !!

**Comment by nvivo** [comment]
@alexcpendleton This seem to have changed on 1.0, as going back to 0.1.3 works fine.

I understand this is not ideal, but is there any reason the parameterless constructor can't just pass these parameters by default? Sounds like this would be the default use for the class.

**Comment by alexcpendleton** [comment]
@nvivo I'll take a look, I'm not sure what would've changed between the two to cause that. If I had written the library today, the default constructor might use that behavior by default, but I don't want to change it on the people already using the library as-is. I'll give it some more thought, but I'm not inclined to change it at this point.

**Comment by nvivo** [comment]
I don't want to complain, this is a good library. But the point is that I have been using this library in a project for 6 months and suddenly it's broken in 1.0 and I'm having to change this call everywhere.

Maybe the package in nuget was not in sync with what was on github, but I guess this is not about changing the behavior, but reverting to what was working before.

**Comment by nvivo** [comment]
Just for reference, using ILSpy, the code from 0.1.3 that is on nuget:

```cs
		public LipsumGenerator()
		{
			this.LipsumText = new StringBuilder(Lipsums.LoremIpsum);
		}
```

The git history here doesn't show when this was changed. But that's what is published in nuget.

**Comment by alexcpendleton** [comment]
Thank you. The Nuget package was uploaded by someone other than myself so it's possible there were some differences, and it seems that there were. For this is what's in the Nuget package then I'll restore it as soon as possible. Much appreciated.

**Comment by alexcpendleton** [comment]
Thanks so much for bringing this to my attention. 1.0.1 is in source and pushed to Nuget. I'm terribly sorry for the mix up here.

**Comment by nvivo** [comment]
Cool. Thanks for fix!
