### ISSUE TITLE
Old code type

### ISSUE THREAD

**Issue by danielrinconr** [alexcpendleton/NLipsum#3]
It code is very old and no have and explanation

**Comment by alexcpendleton** [comment]
Could you please elaborate?

**Comment by danielrinconr** [comment]
It's time to migrate that code to a newer Framework version.

**Comment by danielrinconr** [comment]
I upload a clone repository with some changes. Look it and tell me if you think necessary to make these updates or if you prefer to leave the project in Framework 2.0
