### ISSUE TITLE
Quickstart or examples to get started?

### ISSUE THREAD

**Issue by tarrball** [alexcpendleton/NLipsum#6]
It took me a little digging through the source to figure out how to use this thing. I'd be willing to add a couple examples to the README if that's desirable and there's anybody out there to approve the PR.

**Comment by alexcpendleton** [comment]
I'll approve it eventually! There is also a Wiki page for this, which maybe should just go in the main Readme. Please feel free to add whatever you think would be helpful. 

I appreciate the feedback.
